import type { TourGuide } from "./types";

/**
 * Every walkthrough in the product. Two kinds:
 *  - "overview": the flat, one-step-per-section tour for a portal.
 *  - "module": a sequential guide through one workflow, which may span
 *    several pages and tabs via each step's optional `route`.
 */
export const GUIDES: TourGuide[] = [
  /* ---------------------------------------------------------------- talent */
  {
    id: "talent.overview",
    portal: "talent",
    kind: "overview",
    title: "Vault overview",
    description: "A quick lap of the main sections of your vault.",
    steps: [
      {
        key: "dashboard",
        selector: '[data-tour="/talent"]',
        title: "Dashboard",
        body: "Your home screen — a quick read on what's outstanding, what's expiring and what your Manager has asked for.",
      },
      {
        key: "vault",
        selector: '[data-tour="/talent/vault"]',
        title: "Your Vault",
        body: "Everything you upload lives here — your Private Vault (only you can see it) and the Agency Shared Folder your Manager can access.",
      },
      {
        key: "sharing",
        selector: '[data-tour="/talent/sharing"]',
        title: "Shared Access",
        body: "Give a loved one time-limited access to specific documents. They get a secure link; you give them the access code separately.",
      },
      {
        key: "budget",
        selector: '[data-tour="/talent/budget"]',
        title: "Budget & Income",
        body: "A place to track earnings and spending against your contracts. It's on its way — we'll let you know the moment it opens.",
      },
      {
        key: "needs-attention",
        selector: '[data-tour="needs-attention"]',
        title: "Needs attention",
        body: "Your dashboard surfaces expiring documents and requests from your Manager here. Dismiss anything you've handled.",
      },
      {
        key: "settings",
        selector: '[data-tour="/talent/settings"]',
        title: "Settings",
        body: "Manage which folder categories are active, notification reminders, your password and two-factor authentication.",
      },
    ],
  },
  {
    id: "talent.vault",
    portal: "talent",
    kind: "module",
    title: "Using your Vault",
    description: "What stays private, what your Manager sees, and how to upload.",
    match: ["/talent/vault"],
    steps: [
      {
        key: "tabs",
        route: { to: "/talent/vault", search: { tab: "private" } },
        selector: '[data-tour="talent-vault-tabs"]',
        title: "Two separate places",
        body: "Your Vault has two sides. Private Vault is yours alone — nobody at your agency can open it. Agency Shared Folder is the only area your Manager can see.",
      },
      {
        key: "private",
        route: { to: "/talent/vault", search: { tab: "private" } },
        selector: '[data-tour="talent-vault-body"]',
        title: "Private Vault",
        body: "Personal papers by category — identity, medical, financial and so on. Upload here when a document is for your own records only.",
        optional: true,
      },
      {
        key: "shared",
        route: { to: "/talent/vault", search: { tab: "agency" } },
        selector: '[data-tour="talent-vault-body"]',
        title: "Agency Shared Folder",
        body: "Documents filed here are visible to your Manager, in the folders your agency set up for you. Anything you add is what they'll use for compliance.",
        optional: true,
      },
      {
        key: "ai-review-open",
        route: { to: "/talent/vault", search: { tab: "private" } },
        selector: '[data-tour="talent-vault-upload"]',
        title: "After you upload, the AI reviews it",
        body: "The moment a file you've uploaded to your Private Vault or Agency Shared Folder finishes, the AI filing review popup opens. The document isn't filed yet — the AI reads it and proposes where it belongs, and you have the last word.",
        optional: true,
      },
      {
        key: "ai-review-folder",
        route: { to: "/talent/vault", search: { tab: "private" } },
        selector: '[data-tour="filing-folder"]',
        title: "Folder & subfolder",
        body: "Say you upload a photo of your passport. The AI fills Private Vault folder with \"Identity Documents\" and Subfolder with \"Passports\", and shows a confidence label — high, medium or low. Under the fields the value carries a \"Suggested by AI\" badge with that confidence.",
        optional: true,
      },
      {
        key: "ai-review-source",
        route: { to: "/talent/vault", search: { tab: "private" } },
        selector: '[data-tour="filing-source-toggle"]',
        title: "Where did this come from?",
        body: "Click \"Where did this come from?\" and the exact sentence the AI read from your document is shown — for a passport, something like \"Republic of South Africa — Passport No. M00123456\". If the sentence doesn't support the suggestion, don't trust it.",
        optional: true,
      },
      {
        key: "ai-review-edit",
        route: { to: "/talent/vault", search: { tab: "private" } },
        selector: '[data-tour="filing-subfolder"]',
        title: "The fields are live — just change them",
        body: "There's no approve or reject button. Open the Subfolder dropdown and pick \"Identity cards\" instead, and the badge flips straight to \"Edited by you\". Whatever is sitting in the fields is what gets saved.",
        optional: true,
      },
      {
        key: "ai-review-expiry",
        route: { to: "/talent/vault", search: { tab: "private" } },
        selector: '[data-tour="filing-expiry"]',
        title: "Expiry & reminder",
        body: "The AI also reads expiry dates. On a passport it would set Expiry date to 2031-04-18 and put 30 in \"Remind me this many days before\", so a reminder lands on 2031-03-19. Check the source sentence, correct the date if it's misread, or tick \"No reminder needed for this document\" when the document never expires.",
        optional: true,
      },
      {
        key: "ai-review-save",
        route: { to: "/talent/vault", search: { tab: "private" } },
        selector: '[data-tour="filing-save"]',
        title: "Nothing is filed automatically",
        body: "\"Save filing\" writes exactly what's in the fields at that moment — folder, expiry and reminder. \"Skip for now\" doesn't lose the document: it stays uploaded and waits for you under the Pending review filter, so you can come back when you have the paperwork in front of you.",
        optional: true,
      },
    ],
  },
  {
    id: "talent.sharing",
    portal: "talent",
    kind: "module",
    title: "Sharing with a loved one",
    description: "Generate a secure link, then pass on the access code separately.",
    match: ["/talent/sharing"],
    steps: [
      {
        key: "new",
        route: { to: "/talent/sharing" },
        selector: '[data-tour="talent-share-new"]',
        title: "Create a share",
        body: "Start here. You choose who it's for, what it covers and when it expires — nothing is shared until you set it up deliberately.",
      },
      {
        key: "code",
        route: { to: "/talent/sharing" },
        selector: '[data-tour="talent-share-new"]',
        title: "Send the code separately",
        body: "You'll get a secure link and a separate access code. Send them by different means — the link by email, the code by message or in person — so neither on its own opens anything.",
      },
      {
        key: "manage",
        route: { to: "/talent/sharing" },
        selector: '[data-tour="talent-share-table"]',
        title: "Keep control",
        body: "Active shares are listed here with their expiry and how often they've been viewed. Revoke any of them at once, without warning the recipient.",
        optional: true,
      },
    ],
  },
  {
    id: "talent.settings",
    portal: "talent",
    kind: "module",
    title: "Settings and reminders",
    description: "Folder categories, reminders and your account security.",
    match: ["/talent/settings"],
    steps: [
      {
        key: "tabs",
        route: { to: "/talent/settings" },
        selector: '[data-tour="talent-settings-tabs"]',
        title: "Everything about your account",
        body: "Profile, Account, Security log, Manage folders, Agency Relationship and Notifications each live on their own tab here.",
      },
      {
        key: "folders",
        route: { to: "/talent/settings" },
        selector: '[data-tour="talent-settings-tabs"]',
        title: "Manage folders",
        body: "Choose which folder categories are active in your Private Vault. Switch off what you don't need — nothing is deleted, it's just hidden.",
      },
      {
        key: "notifications",
        route: { to: "/talent/settings" },
        selector: '[data-tour="talent-settings-tabs"]',
        title: "Notifications",
        body: "Set how many days' notice you want before a document expires, and which reminders reach you by email.",
      },
    ],
  },

  /* ---------------------------------------------------------------- agency */
  {
    id: "agency.overview",
    portal: "agency",
    kind: "overview",
    title: "Portal overview",
    description: "A quick lap of the main sections of the agency portal.",
    steps: [
      {
        key: "dashboard",
        selector: '[data-tour="/agency"]',
        title: "Dashboard",
        body: "Your daily overview — roster size, compliance, anything expiring soon and the latest talent activity.",
      },
      {
        key: "talent-roster",
        selector: '[data-tour="/agency/talent"]',
        title: "Talent Roster",
        body: "Every talent you manage, their status and their compliance at a glance.",
      },
      {
        key: "document-vault",
        selector: '[data-tour="/agency/document-vault"]',
        title: "Document Vault",
        body: "Upload, review and request documents. The Requests tab tracks anything you're waiting on from talent.",
      },
      {
        key: "invitations",
        selector: '[data-tour="/agency/invitations"]',
        title: "Invitations",
        body: "Invite new talent and choose the shared folders they'll get the moment they accept.",
      },
      {
        key: "quotes-invoices",
        selector: '[data-tour="/agency/quotes-invoices"]',
        title: "Quotes & Invoices",
        body: "Create quotes, convert them to invoices and track payment. There's a dedicated guide for the full billing workflow.",
      },
      {
        key: "activity-log",
        selector: '[data-tour="/agency/activity"]',
        title: "Activity Log",
        body: "A filterable record of every action on your account — who did what, when, and from which device.",
      },
      {
        key: "agency-profile",
        selector: '[data-tour="/agency/settings"]',
        title: "Agency Profile",
        body: "Your agency details, logo, tax settings and the verified address your billing emails are sent from.",
      },
    ],
  },
  {
    id: "agency.quotes-invoices",
    portal: "agency",
    kind: "module",
    title: "Quotes & Invoices workflow",
    description: "Set up billing, raise a quote, convert it to an invoice and track payment.",
    match: ["/agency/quotes-invoices"],
    steps: [
      {
        key: "settings",
        route: { to: "/agency/settings", search: { tab: "quotes-invoices" } },
        selector: '[data-tour="billing-settings"]',
        title: "Set up before you issue anything",
        body: "Start in Agency Profile → Quotes & Invoices. Set your default acceptance window, reminder cadence, payment terms and overdue grace period here.",
      },
      {
        key: "tax",
        route: { to: "/agency/settings", search: { tab: "quotes-invoices" } },
        selector: '[data-tour="billing-settings"]',
        title: "Tax and branding",
        body: "If you're VAT registered, record your VAT registration number and default VAT rate, plus the billing address and logo that appear on every document you send.",
      },
      {
        key: "create",
        route: { to: "/agency/quotes-invoices" },
        selector: '[data-tour="billing-new"]',
        title: "Create a quote",
        body: "Use New Quote for work you're pricing, and New Invoice only when you're billing directly without a quote first.",
      },
      {
        key: "issue",
        route: { to: "/agency/quotes-invoices" },
        selector: '[data-tour="billing-table"]',
        title: "Issue it to a talent or client",
        body: "Each row records who the document is for and where it was sent. You can add more than one recipient address, and share the document with the linked talent.",
        optional: true,
      },
      {
        key: "convert",
        route: { to: "/agency/quotes-invoices" },
        selector: '[data-tour="billing-convert"]',
        title: "An accepted quote becomes the invoice",
        body: "You never retype an accepted quote. Use the convert action on that quote's own row — the line items, VAT and recipient carry over, and you only confirm the invoice number.",
        optional: true,
      },
      {
        key: "track",
        route: { to: "/agency/quotes-invoices" },
        selector: '[data-tour="billing-summary"]',
        title: "Track the money",
        body: "Quoted, invoiced, received and outstanding for the period you've selected. The quotes tile also shows how many accepted quotes are still waiting to be converted.",
        optional: true,
      },
      {
        key: "reports",
        route: { to: "/agency/quotes-invoices" },
        selector: '[data-tour="billing-subtabs"]',
        title: "Reports",
        body: "The Reports tab breaks the same period down over time and exports to CSV or PDF for your accountant.",
      },
    ],
  },
  {
    id: "agency.document-vault",
    portal: "agency",
    kind: "module",
    title: "Document Vault & requests",
    description: "Upload, request and review talent documents.",
    match: ["/agency/document-vault"],
    steps: [
      {
        key: "navigate",
        route: { to: "/agency/document-vault" },
        selector: '[data-tour="vault-panes"]',
        title: "Talent, then folder, then document",
        body: "Pick a talent on the left, then a folder, then the document. Search across every talent at once from the box at the top.",
        optional: true,
      },
      {
        key: "upload",
        route: { to: "/agency/document-vault" },
        selector: '[data-tour="vault-actions"]',
        title: "Upload to a talent",
        body: "Upload to Talent files a document straight into the talent's shared folders. Request Document asks the talent to supply it themselves.",
      },
      {
        key: "tabs",
        route: { to: "/agency/document-vault" },
        selector: '[data-tour="vault-tabs"]',
        title: "What needs your attention",
        body: "Pending review holds AI-filed documents awaiting confirmation, Needs review is anything flagged, and Expiring lists documents running out of validity.",
      },
      {
        key: "requests",
        route: { to: "/agency/document-vault" },
        selector: '[data-tour="vault-tabs"]',
        title: "The Requests tab",
        body: "Everything you've asked talent for sits here, filtered by All, Needs action, Submitted, Resubmission and Completed. A dot appears when something needs action.",
      },
      {
        key: "new-request",
        route: { to: "/agency/document-vault", search: { tab: "Requests" } },
        selector: '[data-tour="vault-new-request"]',
        title: "Raise a request",
        body: "New request takes the talent, the folder it should land in, a title, a due date and instructions the talent will see.",
        optional: true,
      },
      {
        key: "review",
        route: { to: "/agency/document-vault", search: { tab: "Requests" } },
        selector: '[data-tour="vault-requests-table"]',
        title: "Review what comes back",
        body: "Review a submission and either complete it or ask for a resubmission with a reason. Notes on a resubmission are shown to the talent, so keep them plain.",
        optional: true,
      },
      {
        key: "ai-review-open",
        route: { to: "/agency/document-vault" },
        selector: '[data-tour="vault-actions"]',
        title: "After you upload, review what the AI suggests",
        body: "When an Upload to Talent finishes, the AI filing review popup opens before the document counts as filed. The AI reads the file and proposes where it should go on that talent's record — nothing is written until you save.",
        optional: true,
      },
      {
        key: "ai-review-folder",
        route: { to: "/agency/document-vault" },
        selector: '[data-tour="filing-folder"]',
        title: "Folder & subfolder",
        body: "Upload a scan of a talent's passport and the AI sets Agency Shared Folder folder to \"Identity Documents\" and Subfolder to \"Passports\", with a confidence label of high, medium or low. The value below carries a \"Suggested by AI\" badge showing that confidence.",
        optional: true,
      },
      {
        key: "ai-review-source",
        route: { to: "/agency/document-vault" },
        selector: '[data-tour="filing-source-toggle"]',
        title: "Where did this come from?",
        body: "Click \"Where did this come from?\" to see the verbatim sentence the suggestion was drawn from — for that passport, \"Republic of South Africa — Passport No. M00123456\". If the extract doesn't back the folder, change it.",
        optional: true,
      },
      {
        key: "ai-review-edit",
        route: { to: "/agency/document-vault" },
        selector: '[data-tour="filing-subfolder"]',
        title: "The fields are live, not a proposal",
        body: "There is no accept or reject step. Change the Subfolder dropdown to \"Identity cards\" and the badge immediately reads \"Edited by you\" — your value is what gets written, the suggestion is only a pre-fill.",
        optional: true,
      },
      {
        key: "ai-review-expiry",
        route: { to: "/agency/document-vault" },
        selector: '[data-tour="filing-expiry"]',
        title: "Expiry & reminder",
        body: "The AI also proposes an expiry it read off the document — on a driving licence, Expiry date 2029-07-31 — plus a lead time in \"Remind me this many days before\", say 45, giving a reminder on 2029-06-16. Check the source sentence, correct a misread date, or tick \"No reminder needed for this document\".",
        optional: true,
      },
      {
        key: "ai-review-save",
        route: { to: "/agency/document-vault" },
        selector: '[data-tour="filing-save"]',
        title: "Human validation required",
        body: "Nothing is ever filed automatically. \"Save filing\" writes exactly what's in the fields at that moment. \"Skip for now\" leaves the document queued under the Pending review filter on the tabs you saw earlier, so it's never lost — just waiting.",
        optional: true,
      },
    ],
  },
  {
    id: "agency.invitations",
    portal: "agency",
    kind: "module",
    title: "Inviting talent",
    description: "Invite, choose their folders, send and track.",
    match: ["/agency/invitations"],
    steps: [
      {
        key: "start",
        route: { to: "/agency/invitations" },
        selector: '[data-tour="agency-invite-actions"]',
        title: "Invite talent or staff",
        body: "Invite Talent starts the talent onboarding wizard. Invite Staff adds a colleague to your agency instead. Only the agency owner can send either.",
      },
      {
        key: "folders",
        route: { to: "/agency/invitations" },
        selector: '[data-tour="agency-invite-actions"]',
        title: "Choose their folders",
        body: "Partway through the wizard you pick the shared folders this talent receives — either your standard set or a customised selection. They're created the moment the invitation is accepted.",
      },
      {
        key: "track",
        route: { to: "/agency/invitations" },
        selector: '[data-tour="agency-invite-tabs"]',
        title: "Track and resend",
        body: "Filter by talent, staff, expired or revoked. Each recipient has a unique link, and copying it never extends the expiry — resend if it has lapsed.",
      },
    ],
  },
  {
    id: "agency.folders",
    portal: "agency",
    kind: "module",
    title: "Folders & document rules",
    description: "Set your default folder set, then the retention and expiry rules.",
    match: ["/agency/settings"],
    steps: [
      {
        key: "default-set",
        route: { to: "/agency/settings", search: { tab: "folders" } },
        selector: '[data-tour="manage-folders"]',
        title: "Your standard folder set",
        body: "Default Folder Selection is what every new talent gets unless you customise it during the invitation. Tick the categories your agency actually uses.",
      },
      {
        key: "folder-rules",
        route: { to: "/agency/settings", search: { tab: "folders" } },
        selector: '[data-tour="manage-folders"]',
        title: "Folder rules and subfolders",
        body: "Per category you can add subfolders, set the default validity rule and decide whether AI filing may place documents there.",
      },
      {
        key: "retention",
        route: { to: "/agency/settings", search: { tab: "document-rules" } },
        selector: '[data-tour="document-rules"]',
        title: "Retention rules",
        body: "Document Rules holds folder retention rules and per-document overrides — how many years a document must be kept before it can be removed.",
      },
      {
        key: "notice",
        route: { to: "/agency/settings", search: { tab: "document-rules" } },
        selector: '[data-tour="document-rules"]',
        title: "Expiry notice period",
        body: "Expiring-document notifications set how many days' notice you and your talent get before something lapses, so renewals are chased in time.",
      },
    ],
  },

  /* ----------------------------------------------------------------- admin */
  {
    id: "admin.overview",
    portal: "admin",
    kind: "overview",
    title: "Portal overview",
    description: "A quick lap of the main sections of the admin portal.",
    steps: [
      {
        key: "dashboard",
        selector: '[data-tour="/admin"]',
        title: "Dashboard",
        body: "Platform health at a glance — agencies, active talent, outstanding invites and anything needing review.",
      },
      {
        key: "agencies",
        selector: '[data-tour="/admin/agencies"]',
        title: "Agencies",
        body: "Every agency on the platform — activate, suspend and inspect their setup from here.",
      },
      {
        key: "invitations",
        selector: '[data-tour="/admin/invitations"]',
        title: "Agency Invitations",
        body: "Create and track agency invites, edit the invitation email and send or copy the secure link.",
      },
      {
        key: "quotes-invoices",
        selector: '[data-tour="/admin/quotes-invoices"]',
        title: "Quotes & Invoices",
        body: "Billing activity across the platform, aggregated from what agencies have quoted, invoiced and collected.",
      },
      {
        key: "administrators",
        selector: '[data-tour="/admin/administrators"]',
        title: "Administrators",
        body: "Manage who has platform admin access and their two-factor enrolment.",
      },
      {
        key: "audit",
        selector: '[data-tour="/admin/audit"]',
        title: "Audit & Support Log",
        body: "A full, filterable record of every privileged action, with IP and device details.",
      },
    ],
  },
  {
    id: "admin.invitations",
    portal: "admin",
    kind: "module",
    title: "Agency invitation workflow",
    description: "Create an invitation, edit its email, then send or copy the link.",
    match: ["/admin/invitations"],
    steps: [
      {
        key: "create",
        route: { to: "/admin/invitations" },
        selector: '[data-tour="admin-invite-actions"]',
        title: "Create the invitation",
        body: "Start here with the agency's name and the contact address the invitation is issued to.",
      },
      {
        key: "template",
        route: { to: "/admin/invitations" },
        selector: '[data-tour="admin-invite-table"]',
        title: "Edit the email before it goes",
        body: "Each invitation has its own preview screen where you can adjust the wording before anything is sent.",
        optional: true,
      },
      {
        key: "send",
        route: { to: "/admin/invitations" },
        selector: '[data-tour="admin-invite-table"]',
        title: "Send or copy the secure link",
        body: "Send it by email, or copy the unique link and pass it on yourself. Copying never extends the expiry — resend once it has lapsed.",
        optional: true,
      },
      {
        key: "status",
        route: { to: "/admin/invitations" },
        selector: '[data-tour="admin-invite-kpis"]',
        title: "Where each one stands",
        body: "The tiles filter the list to all, pending, accepted or expired invitations.",
        optional: true,
      },
    ],
  },
  {
    id: "admin.agencies",
    portal: "admin",
    kind: "module",
    title: "Managing agencies",
    description: "Inspect an agency, then activate or suspend it.",
    match: ["/admin/agencies"],
    steps: [
      {
        key: "list",
        route: { to: "/admin/agencies" },
        selector: '[data-tour="admin-agency-table"]',
        title: "Every agency on the platform",
        body: "Status, contact and setup progress per agency. Open one to see its members, talent and compliance detail.",
        optional: true,
      },
      {
        key: "suspend",
        route: { to: "/admin/agencies" },
        selector: '[data-tour="admin-agency-table"]',
        title: "Suspending an agency",
        body: "Suspending blocks active actions but preserves read-only access and export. You must give a reason, and it's written to the audit log.",
        optional: true,
      },
      {
        key: "actions",
        route: { to: "/admin/agencies" },
        selector: '[data-tour="admin-agency-actions"]',
        title: "Adding an agency",
        body: "New agencies normally arrive through an invitation, so most of your work here is reviewing and reinstating rather than creating.",
      },
    ],
  },
  {
    id: "admin.quotes-invoices",
    portal: "admin",
    kind: "module",
    title: "Platform billing oversight",
    description: "Read-only view of what agencies have quoted and collected.",
    match: ["/admin/quotes-invoices"],
    steps: [
      {
        key: "readonly",
        route: { to: "/admin/quotes-invoices" },
        selector: '[data-tour="admin-billing-header"]',
        title: "Oversight only",
        body: "These figures are aggregated from the agencies' own billing. Nothing here is editable — quotes and invoices are created and sent by each agency in their own portal.",
      },
      {
        key: "totals",
        route: { to: "/admin/quotes-invoices" },
        selector: '[data-tour="admin-billing-kpis"]',
        title: "Platform totals",
        body: "Quoted, invoiced, received and outstanding across every agency for the period you select.",
        optional: true,
      },
      {
        key: "table",
        route: { to: "/admin/quotes-invoices" },
        selector: '[data-tour="admin-billing-table"]',
        title: "Document-level detail",
        body: "Each row shows the issuing agency, the document and its status, so you can trace a figure back to its source.",
        optional: true,
      },
    ],
  },
];
