import type { TourGuide } from "./types";

/**
 * Every walkthrough in the product. Two kinds:
 *  - "overview": the flat, one-step-per-section tour for a portal.
 *  - "module": a sequential, step-by-step manual through one workflow, which
 *    may span several pages and tabs via each step's optional `route`.
 *
 * Module guides are written as worked examples: each step names the real
 * field or button on screen, in the order you touch it, with a plausible
 * value to type in. Keep them that way — a step that only describes what a
 * section "is" belongs in an overview guide, not here.
 */
export const GUIDES: TourGuide[] = [
  /* ---------------------------------------------------------------- talent */
  {
    id: "talent.overview",
    portal: "talent",
    kind: "overview",
    title: "Vault overview",
    description: "A quick lap of the main sections of your vault.",
    steps: [
      {
        key: "dashboard",
        selector: '[data-tour="/talent"]',
        title: "Dashboard",
        body: "Your home screen — a quick read on what's outstanding, what's expiring and what your Manager has asked for.",
      },
      {
        key: "vault",
        selector: '[data-tour="/talent/vault"]',
        title: "Your Vault",
        body: "Everything you upload lives here — your Private Vault (only you can see it) and the Agency Shared Folder your Manager can access.",
      },
      {
        key: "sharing",
        selector: '[data-tour="/talent/sharing"]',
        title: "Shared Access",
        body: "Give a loved one time-limited access to specific documents. They get a secure link; you give them the access code separately.",
      },
      {
        key: "budget",
        selector: '[data-tour="/talent/budget"]',
        title: "Budget & Income",
        body: "A place to track earnings and spending against your contracts. It's on its way — we'll let you know the moment it opens.",
      },
      {
        key: "needs-attention",
        selector: '[data-tour="needs-attention"]',
        title: "Needs attention",
        body: "Your dashboard surfaces expiring documents and requests from your Manager here. Dismiss anything you've handled.",
      },
      {
        key: "settings",
        selector: '[data-tour="/talent/settings"]',
        title: "Settings",
        body: "Manage which folder categories are active, notification reminders, your password and two-factor authentication.",
      },
    ],
  },
  {
    id: "talent.vault",
    portal: "talent",
    kind: "module",
    title: "Using your Vault",
    description: "Upload a document end to end, from choosing the right side of the vault to filing it.",
    match: ["/talent/vault"],
    steps: [
      {
        key: "tabs",
        route: { to: "/talent/vault", search: { tab: "private" } },
        selector: '[data-tour="talent-vault-tabs"]',
        title: "Step 1 — decide which side it belongs on",
        body: "Before you upload anything, pick the tab. Private Vault is yours alone — nobody at your agency can open it. Agency Shared Folder is the only area your Manager can see. Worked example: your marriage certificate goes in Private Vault; the passport your Manager needs for a visa goes in Agency Shared Folder.",
      },
      {
        key: "private-folder",
        route: { to: "/talent/vault", search: { tab: "private" } },
        selector: '[data-tour="talent-vault-body"]',
        title: "Step 2 — open the folder you're filing into",
        body: "Under \"Private Vault Folders\", click the folder — say \"Identity Documents\" — to expand it. Its subfolders appear beneath it (\"Passports\", \"Identity cards\"). Each folder row has its own \"Upload here\" button, which files straight into that folder so you don't have to pick it again later.",
        optional: true,
      },
      {
        key: "private-upload",
        route: { to: "/talent/vault", search: { tab: "private" } },
        selector: '[data-tour="talent-vault-upload"]',
        title: "Step 3 — upload the file",
        body: "Click \"Upload here\" on the Identity Documents row (or the plain \"Upload\" button at the top if you'd rather file it afterwards) and choose the file — for example passport-2026.pdf. The file is checked before it's accepted: it must be a real PDF or image and under the size limit, so a renamed .exe is rejected on the spot.",
        optional: true,
      },
      {
        key: "private-list",
        route: { to: "/talent/vault", search: { tab: "private" } },
        selector: '[data-tour="talent-vault-body"]',
        title: "Step 4 — check it landed",
        body: "Scroll to \"All private documents\". The new row shows Document, Folder, Size and Uploaded — \"passport-2026.pdf · Identity Documents · 1.2 MB · today\". Use \"Search private documents…\" or the folder dropdown (including \"Unfiled\") if you can't see it.",
        optional: true,
      },
      {
        key: "shared",
        route: { to: "/talent/vault", search: { tab: "agency" } },
        selector: '[data-tour="talent-vault-body"]',
        title: "Step 5 — the Agency Shared Folder works the same way",
        body: "Switch to Agency Shared Folder and repeat: open the folder, upload, confirm. The difference is the extra Status and Expires columns — a document your Manager hasn't checked yet reads \"Pending review\" until they confirm it. Anything filed here is what your agency uses for compliance.",
        optional: true,
      },
      {
        key: "requests",
        route: { to: "/talent/vault", search: { tab: "requests" } },
        selector: '[data-tour="talent-vault-body"]',
        title: "Step 6 — responding to a request",
        body: "Under \"Open requests\", each card names what your Manager asked for and when it's due. Click \"Upload response\" on that card and the document is attached to the request itself, not just dropped in a folder. If the card reads \"Manager requested a resubmission\", their reason is shown above the button and the button reads \"Resubmit\" — previous submissions stay in \"Recent history\", nothing is deleted.",
        optional: true,
      },
      {
        key: "ai-review-open",
        route: { to: "/talent/vault", search: { tab: "private" } },
        selector: '[data-tour="talent-vault-upload"]',
        title: "After you upload, the AI reviews it",
        body: "The moment a file you've uploaded to your Private Vault or Agency Shared Folder finishes, the AI filing review popup opens. The document isn't filed yet — the AI reads it and proposes where it belongs, and you have the last word.",
        optional: true,
      },
      {
        key: "ai-review-folder",
        route: { to: "/talent/vault", search: { tab: "private" } },
        selector: '[data-tour="filing-folder"]',
        title: "Folder & subfolder",
        body: "Say you upload a photo of your passport. The AI fills Private Vault folder with \"Identity Documents\" and Subfolder with \"Passports\", and shows a confidence label — high, medium or low. Under the fields the value carries a \"Suggested by AI\" badge with that confidence.",
        optional: true,
      },
      {
        key: "ai-review-source",
        route: { to: "/talent/vault", search: { tab: "private" } },
        selector: '[data-tour="filing-source-toggle"]',
        title: "Where did this come from?",
        body: "Click \"Where did this come from?\" and the exact sentence the AI read from your document is shown — for a passport, something like \"Republic of South Africa — Passport No. M00123456\". If the sentence doesn't support the suggestion, don't trust it.",
        optional: true,
      },
      {
        key: "ai-review-edit",
        route: { to: "/talent/vault", search: { tab: "private" } },
        selector: '[data-tour="filing-subfolder"]',
        title: "The fields are live — just change them",
        body: "There's no approve or reject button. Open the Subfolder dropdown and pick \"Identity cards\" instead, and the badge flips straight to \"Edited by you\". Whatever is sitting in the fields is what gets saved.",
        optional: true,
      },
      {
        key: "ai-review-expiry",
        route: { to: "/talent/vault", search: { tab: "private" } },
        selector: '[data-tour="filing-expiry"]',
        title: "Expiry & reminder",
        body: "The AI also reads expiry dates. On a passport it would set Expiry date to 2031-04-18 and put 30 in \"Remind me this many days before\", so a reminder lands on 2031-03-19. Check the source sentence, correct the date if it's misread, or tick \"No reminder needed for this document\" when the document never expires.",
        optional: true,
      },
      {
        key: "ai-review-save",
        route: { to: "/talent/vault", search: { tab: "private" } },
        selector: '[data-tour="filing-save"]',
        title: "Nothing is filed automatically",
        body: "\"Save filing\" writes exactly what's in the fields at that moment — folder, expiry and reminder. \"Skip for now\" doesn't lose the document: it stays uploaded and waits for you under the Pending review filter, so you can come back when you have the paperwork in front of you.",
        optional: true,
      },
    ],
  },
  {
    id: "talent.sharing",
    portal: "talent",
    kind: "module",
    title: "Sharing with a loved one",
    description: "Create one secure share, field by field, then hand over the code safely.",
    match: ["/talent/sharing"],
    steps: [
      {
        key: "new",
        route: { to: "/talent/sharing" },
        selector: '[data-tour="talent-share-new"]',
        title: "Step 1 — start the share",
        body: "On Shared Access, click the new share button. Nothing is shared until you finish this form deliberately — there is no automatic sharing anywhere in TalVault.",
      },
      {
        key: "recipient",
        route: { to: "/talent/sharing" },
        selector: '[data-tour="share-recipient"]',
        title: "Step 2 — who it's for, and for how long",
        body: "Fill the four fields at the top in order. Loved One name: \"Sarah Mokoena\". Email (link is sent here): \"sarah@example.com\". Relationship: \"Spouse\". Access duration (days): 14 — the share stops working on its own after that, you don't have to remember to close it.",
        optional: true,
      },
      {
        key: "scope",
        route: { to: "/talent/sharing" },
        selector: '[data-tour="share-scope"]',
        title: "Step 3 — what are you sharing?",
        body: "Choose \"Whole folders\" and tick only the folders they need — say \"Insurance\" and \"Medical\" — or choose \"A single document\", type \"policy\" into \"Search your documents…\" and select the one row. Share the least you can get away with; you can always create a second share later.",
        optional: true,
      },
      {
        key: "permission",
        route: { to: "/talent/sharing" },
        selector: '[data-tour="share-permission"]',
        title: "Step 4 — what can they do?",
        body: "\"View only (watermarked)\" opens documents in a viewer stamped with their email and the time, and downloads are blocked on the server, not just hidden. Pick \"View & download\" only when they genuinely need their own copy — for example an advisor filing a claim.",
        optional: true,
      },
      {
        key: "note",
        route: { to: "/talent/sharing" },
        selector: '[data-tour="share-permission"]',
        title: "Step 5 — note, email and create",
        body: "Optional note: \"Insurance papers for the claim — call me if anything is missing.\" Leave \"Email the link to Sarah Mokoena\" ticked to send the link straight to her — the access code is never emailed. Then click \"Create secure share\".",
        optional: true,
      },
      {
        key: "code",
        route: { to: "/talent/sharing" },
        selector: '[data-tour="talent-share-new"]',
        title: "Step 6 — copy the code now, send it separately",
        body: "The confirmation panel is headed \"Shown once — copy it now\": it holds the Magic link and a separate access code. Copy the code before you close it — it is never shown again. Send the link and the code by different means, for example the link by email and the code by phone call, so neither on its own opens anything. Click \"Done\" when you've done both.",
        optional: true,
      },
      {
        key: "manage",
        route: { to: "/talent/sharing" },
        selector: '[data-tour="talent-share-table"]',
        title: "Step 7 — check and revoke",
        body: "The table lists Recipient, Scope, Access, Expires, Views and Status. If \"Views\" climbs faster than you expect, or the claim is settled early, revoke that row's share immediately — the link dies at once and the recipient isn't warned.",
        optional: true,
      },
    ],
  },
  {
    id: "talent.settings",
    portal: "talent",
    kind: "module",
    title: "Settings and reminders",
    description: "Tidy your folder list and set how early you're warned about expiry.",
    match: ["/talent/settings"],
    steps: [
      {
        key: "tabs",
        route: { to: "/talent/settings" },
        selector: '[data-tour="talent-settings-tabs"]',
        title: "Step 1 — find the right tab",
        body: "Settings has six tabs, left to right: Profile, Account, Security log, Manage folders, Agency Relationship and Notifications. Profile holds Full Name, Email and Talent Type; Account holds your password and two-factor authentication; Security log lists every sign-in.",
      },
      {
        key: "profile",
        route: { to: "/talent/settings" },
        selector: '[data-tour="talent-settings-tabs"]',
        title: "Step 2 — set Talent Type first",
        body: "On Profile, set Talent Type — for example \"Actor\" — and save. It isn't cosmetic: it decides which folder categories your agency offers you, so setting it before you tidy your folders saves doing the job twice.",
      },
      {
        key: "folders",
        route: { to: "/talent/settings" },
        selector: '[data-tour="talent-settings-tabs"]',
        title: "Step 3 — Manage folders",
        body: "Open Manage folders and untick the categories you'll never use — if you have no dependants, switch \"Guardianship\" off. Nothing is deleted; the category is hidden from your Private Vault, and ticking it again brings it back with its documents intact.",
      },
      {
        key: "notifications",
        route: { to: "/talent/settings" },
        selector: '[data-tour="talent-settings-tabs"]',
        title: "Step 4 — Notifications",
        body: "On Notifications, set \"Warn me before a document expires\" to 60 days ahead — a passport expiring 2031-04-18 then appears on your dashboard from 2031-02-17 — and press Save. That number drives the \"Expiring soon\" tile.",
      },
      {
        key: "in-app",
        route: { to: "/talent/settings" },
        selector: '[data-tour="talent-settings-tabs"]',
        title: "Step 5 — in-app reminders",
        body: "Below that, the \"In-app reminders\" cards control what appears in the \"Needs attention\" panel on your dashboard. Cards marked \"Active\" can be ticked; those marked \"Soon\" are switched off until the TalVault sending domain is verified, so email delivery isn't running yet.",
      },
    ],
  },

  /* ---------------------------------------------------------------- agency */
  {
    id: "agency.overview",
    portal: "agency",
    kind: "overview",
    title: "Portal overview",
    description: "A quick lap of the main sections of the agency portal.",
    steps: [
      {
        key: "dashboard",
        selector: '[data-tour="/agency"]',
        title: "Dashboard",
        body: "Your daily overview — roster size, compliance, anything expiring soon and the latest talent activity.",
      },
      {
        key: "talent-roster",
        selector: '[data-tour="/agency/talent"]',
        title: "Talent Roster",
        body: "Every talent you manage, their status and their compliance at a glance.",
      },
      {
        key: "document-vault",
        selector: '[data-tour="/agency/document-vault"]',
        title: "Document Vault",
        body: "Upload, review and request documents. The Requests tab tracks anything you're waiting on from talent.",
      },
      {
        key: "invitations",
        selector: '[data-tour="/agency/invitations"]',
        title: "Invitations",
        body: "Invite new talent and choose the shared folders they'll get the moment they accept.",
      },
      {
        key: "quotes-invoices",
        selector: '[data-tour="/agency/quotes-invoices"]',
        title: "Quotes & Invoices",
        body: "Create quotes, convert them to invoices and track payment. There's a dedicated guide for the full billing workflow.",
      },
      {
        key: "activity-log",
        selector: '[data-tour="/agency/activity"]',
        title: "Activity Log",
        body: "A filterable record of every action on your account — who did what, when, and from which device.",
      },
      {
        key: "agency-profile",
        selector: '[data-tour="/agency/settings"]',
        title: "Agency Profile",
        body: "Your agency details, logo, tax settings and the verified address your billing emails are sent from.",
      },
    ],
  },
  {
    id: "agency.quotes-invoices",
    portal: "agency",
    kind: "module",
    title: "Quotes & Invoices workflow",
    description: "A worked example: settings, a R12,000 quote, converting it, getting paid, reporting.",
    match: ["/agency/quotes-invoices"],
    steps: [
      {
        key: "settings-terms",
        route: { to: "/agency/settings", search: { tab: "quotes-invoices" } },
        selector: '[data-tour="billing-settings"]',
        title: "Step 1 — set your defaults before you bill anyone",
        body: "Agency Profile → Quotes & Invoices. Under \"Quote Acceptance\" put 14 in \"Default acceptance window (days)\" and 7 in \"Reminder cadence (days before expiry)\". Under \"Invoice Payment\" put 30 in \"Default payment terms (days)\" and 3 in \"Overdue grace period (days)\". Every new document is pre-filled from these, so you set them once.",
      },
      {
        key: "settings-vat",
        route: { to: "/agency/settings", search: { tab: "quotes-invoices" } },
        selector: '[data-tour="billing-settings"]',
        title: "Step 2 — VAT / Tax",
        body: "If you're registered, tick \"Registered for VAT (show \"Tax Invoice\")\", type your VAT registration number — e.g. 4123456789 — and set \"Default VAT rate (%)\" to 15. That 15% becomes the pre-filled VAT % on every new line item, and documents are headed \"Tax Invoice\" rather than \"Invoice\".",
      },
      {
        key: "settings-branding",
        route: { to: "/agency/settings", search: { tab: "quotes-invoices" } },
        selector: '[data-tour="billing-settings"]',
        title: "Step 3 — branding and sender, then Save settings",
        body: "Under \"Branding\", type your \"Billing address (appears on documents)\" — \"12 Long Street, Gardens, Cape Town, 8001\" — click Upload for the agency logo (PNG/JPG/SVG/WEBP, max 2 MB) and pick an accent colour. Check the sender card at the top: until your own address is verified, documents go out from the TalVault system address. Finish with \"Save settings\".",
      },
      {
        key: "new-quote",
        route: { to: "/agency/quotes-invoices" },
        selector: '[data-tour="billing-new"]',
        title: "Step 4 — click New Quote",
        body: "Back on Quotes & Invoices, use \"New Quote\" for work you're pricing. \"New Invoice\" is only for billing with no quote first. The editor opens headed \"New quote\", with Type already set to Quote and Number left blank — leave it blank, a real number is allocated when you send.",
      },
      {
        key: "editor-ref",
        route: { to: "/agency/quotes-invoices" },
        selector: '[data-tour="editor-ref"]',
        title: "Step 5 — Reference / description",
        body: "Type what the job actually is: \"Brand campaign — Autumn 2026\". This is what you'll recognise the row by in the workspace table and in the search box, so make it specific — \"Shoot\" will not help you in three months.",
        optional: true,
      },
      {
        key: "editor-client",
        route: { to: "/agency/quotes-invoices" },
        selector: '[data-tour="editor-client"]',
        title: "Step 6 — who it's for",
        body: "Client / recipient name: \"Kalahari Retail Group\". Talent: \"Naledi Khumalo\" — type the talent's name exactly as it appears on your roster, because that's what links the document to them and lets you share it with them later. Then \"Recipient billing address\": \"5 Rivonia Road, Sandton, 2196\" — SARS requires it on invoices over R5,000 — and \"Recipient VAT number\" if they have one.",
        optional: true,
      },
      {
        key: "editor-recipients",
        route: { to: "/agency/quotes-invoices" },
        selector: '[data-tour="editor-recipients"]',
        title: "Step 7 — Recipient emails",
        body: "Type \"accounts@kalahariretail.co.za\" and press Enter to turn it into a chip, then add \"thandi@kalahariretail.co.za\" the same way. Every chip receives the document when you send. An address with no chip around it hasn't been added — press Enter.",
        optional: true,
      },
      {
        key: "editor-dates",
        route: { to: "/agency/quotes-invoices" },
        selector: '[data-tour="editor-ref"]',
        title: "Step 8 — dates and window",
        body: "Issued defaults to today. On a quote the next date field is labelled \"Valid until\" — set 2026-09-14 — and \"Acceptance window (days)\" is already 14 from your settings. Currency stays ZAR. Leave Status on Draft; sending changes it for you.",
        optional: true,
      },
      {
        key: "editor-lines",
        route: { to: "/agency/quotes-invoices" },
        selector: '[data-tour="editor-add-line"]',
        title: "Step 9 — line items",
        body: "First line: Description \"Full-day shoot\", Qty 1, Unit price (excl.) 10000, VAT % 15 — Line total reads R11,500.00. Click \"Add line\" and add \"Wardrobe & travel\", Qty 1, Unit price 2000, VAT % 15. Prices are entered excluding VAT; the trash icon on a row removes it.",
        optional: true,
      },
      {
        key: "editor-totals",
        route: { to: "/agency/quotes-invoices" },
        selector: '[data-tour="editor-totals"]',
        title: "Step 10 — check the totals",
        body: "The footer computes it for you: Subtotal (excl.) R12,000.00, VAT R1,800.00, Total R13,800.00. VAT is applied per line, so a zero-rated line can sit next to a 15% one. If the total looks wrong, the culprit is nearly always a Qty or a VAT % on one line.",
        optional: true,
      },
      {
        key: "editor-notes",
        route: { to: "/agency/quotes-invoices" },
        selector: '[data-tour="editor-totals"]',
        title: "Step 11 — notes and sharing",
        body: "\"Notes / terms\": \"50% deposit on acceptance, balance on delivery of final assets.\" Tick \"Share with linked talent\" so Naledi can see the quote in her own portal. On an invoice you'd also see \"Allow partial payment\" — tick it when you've agreed a deposit.",
        optional: true,
      },
      {
        key: "editor-send",
        route: { to: "/agency/quotes-invoices" },
        selector: '[data-tour="editor-actions"]',
        title: "Step 12 — preview, save, send",
        body: "Click \"Preview\" to see the document exactly as the client receives it — logo, VAT number, line items and the address it's sent from. Close it, click \"Save draft\", then send from the preview: the number is allocated (QT-2026-0001), the status flips to Sent, and you're told how many of your recipients it reached.",
        optional: true,
      },
      {
        key: "track-status",
        route: { to: "/agency/quotes-invoices" },
        selector: '[data-tour="billing-table"]',
        title: "Step 13 — mark it accepted",
        body: "The row now reads QT-2026-0001 · Quote · Naledi Khumalo · Kalahari Retail Group, with \"Accept within 14 days\" under \"Acceptance / Due Rule\". When the client says yes, change the Status dropdown in that row to Accepted. Use the chips above the table — Quote drafts, Quotes sent, Accepted, Partial, Late — to filter rather than scrolling.",
        optional: true,
      },
      {
        key: "convert",
        route: { to: "/agency/quotes-invoices" },
        selector: '[data-tour="billing-convert"]',
        title: "Step 14 — convert it to an invoice",
        body: "Never retype an accepted quote. On the quote's own row, click the convert icon (two arrows) at the right — it only appears while the quote has no invoice yet. Confirm, and INV-2026-0001 is created with both line items, the 15% VAT, the client and the recipients carried over. The quote row then shows a green \"→ INV-2026-0001\" chip and the invoice shows \"← QT-2026-0001\".",
        optional: true,
      },
      {
        key: "payment",
        route: { to: "/agency/quotes-invoices" },
        selector: '[data-tour="billing-table"]',
        title: "Step 15 — record payment",
        body: "When the deposit lands, set the invoice's Status dropdown to Partial; when the balance clears, set it to Paid. The rule column tracks it — \"Payment due in 30 days\", then \"Overdue by 4 days\" if it slips. Overdue is not applied automatically: you mark it, using the grace period you set in Step 1 as your cue.",
        optional: true,
      },
      {
        key: "summary",
        route: { to: "/agency/quotes-invoices" },
        selector: '[data-tour="billing-summary"]',
        title: "Step 16 — read the money back",
        body: "Set Period to \"This month\" and the four cards answer it: Total Quoted R13,800.00, Total Invoiced R13,800.00, Total Received R6,900.00, Total Outstanding R6,900.00. The \"Quotes Accepted\" tile below carries the line that matters most — \"1 ready to convert\" means an accepted quote you haven't invoiced yet.",
        optional: true,
      },
      {
        key: "reports",
        route: { to: "/agency/quotes-invoices" },
        selector: '[data-tour="billing-subtabs"]',
        title: "Step 17 — the Reports subtab",
        body: "Click Reports. Set Period to \"Last quarter\" (or Custom and enter your own from/to dates) and you get the invoiced-versus-received chart plus \"Breakdown by talent\" and \"Breakdown by client\".",
      },
      {
        key: "export",
        route: { to: "/agency/quotes-invoices" },
        selector: '[data-tour="billing-export"]',
        title: "Step 18 — export for your accountant",
        body: "\"Export CSV\" downloads every line item in the period as a spreadsheet; \"Export PDF\" opens the print dialog for a formatted statement — allow pop-ups or nothing happens. Both use the period on screen, so set the period first.",
        optional: true,
      },
    ],
  },
  {
    id: "agency.document-vault",
    portal: "agency",
    kind: "module",
    title: "Document Vault & requests",
    description: "Upload for a talent, chase what's missing and review what comes back.",
    match: ["/agency/document-vault"],
    steps: [
      {
        key: "navigate",
        route: { to: "/agency/document-vault" },
        selector: '[data-tour="vault-panes"]',
        title: "Step 1 — talent, then folder, then document",
        body: "The Vault is three panes. Click \"Naledi Khumalo\" under \"Select a talent\", then a folder such as \"Identity Documents\" to expand it, then the document. A folder carrying an amber \"Folder needs review\" pill has something waiting on you inside.",
        optional: true,
      },
      {
        key: "search",
        route: { to: "/agency/document-vault" },
        selector: '[data-tour="vault-panes"]',
        title: "Step 2 — or search the whole roster at once",
        body: "If you don't know whose it is, type into \"Search every document, talent or folder...\" — \"passport\" returns matching rows across every talent with columns Document, Talent, Folder, Status and Validity, so you can skip the panes entirely.",
        optional: true,
      },
      {
        key: "upload",
        route: { to: "/agency/document-vault" },
        selector: '[data-tour="vault-actions"]',
        title: "Step 3 — Upload document",
        body: "Click the upload action and the \"Upload document\" dialog opens. Confirm Talent reads \"Naledi Khumalo\", then choose the Destination folder.",
      },
      {
        key: "upload-folder",
        route: { to: "/agency/document-vault" },
        selector: '[data-tour="vault-actions"]',
        title: "Step 4 — Allowed vs Blocked folders",
        body: "In \"Destination folder\", folders in the Roster Shared Folder are tagged green \"Allowed\". Folders that live in the talent's Private Vault are tagged amber \"Blocked\" and can't be selected — as a Manager you cannot put anything into a talent's private space, by design. Pick \"Identity Documents\".",
        optional: true,
      },
      {
        key: "upload-fields",
        route: { to: "/agency/document-vault" },
        selector: '[data-tour="vault-actions"]',
        title: "Step 5 — name, status, expiry",
        body: "\"Document name (optional)\": \"Passport — Naledi Khumalo\" (leave it blank to keep the file name). Status: \"Needs review\" if you still have to check it, \"Filed\" if you're certain. Expiry (optional): 2031-04-18. Then upload.",
        optional: true,
      },
      {
        key: "tabs",
        route: { to: "/agency/document-vault" },
        selector: '[data-tour="vault-tabs"]',
        title: "Step 6 — work the queues",
        body: "The tabs are your work list. Pending review holds AI-filed documents awaiting confirmation, Needs review is anything flagged, and Expiring lists documents running out of validity inside the notice period set in Agency Profile → Document Rules. Clear these three and your roster is compliant.",
      },
      {
        key: "requests",
        route: { to: "/agency/document-vault", search: { tab: "Requests" } },
        selector: '[data-tour="vault-tabs"]',
        title: "Step 7 — the Requests tab",
        body: "Everything you've asked talent for sits here, filtered by All, Needs action, Submitted, Resubmission and Completed. A dot on the tab means at least one submission is waiting on you.",
      },
      {
        key: "new-request",
        route: { to: "/agency/document-vault", search: { tab: "Requests" } },
        selector: '[data-tour="vault-new-request"]',
        title: "Step 8 — raise a request",
        body: "Click \"New document request\" and work down the form: Talent \"Naledi Khumalo\"; Folder \"Identity Documents\" (where the submission will land); Title 'Updated passport scan'; Due date 2026-09-30; Instructions \"Please send the photo page in colour — all four corners visible.\" The talent sees the title, date and instructions verbatim, so write them as you'd say them.",
        optional: true,
      },
      {
        key: "review-open",
        route: { to: "/agency/document-vault", search: { tab: "Requests" } },
        selector: '[data-tour="vault-requests-table"]',
        title: "Step 9 — open the submission",
        body: "The table lists Title, Talent, Folder, Due and Status. When Naledi responds, her row moves to Submitted — click \"Review\" on it. The panel shows the current status, the instructions you sent and the file she uploaded.",
        optional: true,
      },
      {
        key: "review-outcome",
        route: { to: "/agency/document-vault", search: { tab: "Requests" } },
        selector: '[data-tour="request-outcome"]',
        title: "Step 10 — choose an outcome",
        body: "Under \"Outcome\" pick one of three: \"Complete\" (accepted, request closes), \"Resubmission required\" (back to the talent), or \"Cancel request\" (no longer needed). Choosing resubmission reveals \"Reason (required)\" — pick the reason code that fits, e.g. an unreadable scan.",
        optional: true,
      },
      {
        key: "review-notes",
        route: { to: "/agency/document-vault", search: { tab: "Requests" } },
        selector: '[data-tour="request-outcome"]',
        title: "Step 11 — write the note the talent reads",
        body: "On a resubmission the Notes field is marked \"(shown to talent)\". Write plainly what to fix: \"The bottom corner is cut off — please re-scan the full photo page.\" Submit, and her card reads \"Manager requested a resubmission\" with your note; her old submission is kept in history, not overwritten.",
        optional: true,
      },
      {
        key: "ai-review-open",
        route: { to: "/agency/document-vault" },
        selector: '[data-tour="vault-actions"]',
        title: "After you upload, review what the AI suggests",
        body: "When an Upload to Talent finishes, the AI filing review popup opens before the document counts as filed. The AI reads the file and proposes where it should go on that talent's record — nothing is written until you save.",
        optional: true,
      },
      {
        key: "ai-review-folder",
        route: { to: "/agency/document-vault" },
        selector: '[data-tour="filing-folder"]',
        title: "Folder & subfolder",
        body: "Upload a scan of a talent's passport and the AI sets Agency Shared Folder folder to \"Identity Documents\" and Subfolder to \"Passports\", with a confidence label of high, medium or low. The value below carries a \"Suggested by AI\" badge showing that confidence.",
        optional: true,
      },
      {
        key: "ai-review-source",
        route: { to: "/agency/document-vault" },
        selector: '[data-tour="filing-source-toggle"]',
        title: "Where did this come from?",
        body: "Click \"Where did this come from?\" to see the verbatim sentence the suggestion was drawn from — for that passport, \"Republic of South Africa — Passport No. M00123456\". If the extract doesn't back the folder, change it.",
        optional: true,
      },
      {
        key: "ai-review-edit",
        route: { to: "/agency/document-vault" },
        selector: '[data-tour="filing-subfolder"]',
        title: "The fields are live, not a proposal",
        body: "There is no accept or reject step. Change the Subfolder dropdown to \"Identity cards\" and the badge immediately reads \"Edited by you\" — your value is what gets written, the suggestion is only a pre-fill.",
        optional: true,
      },
      {
        key: "ai-review-expiry",
        route: { to: "/agency/document-vault" },
        selector: '[data-tour="filing-expiry"]',
        title: "Expiry & reminder",
        body: "The AI also proposes an expiry it read off the document — on a driving licence, Expiry date 2029-07-31 — plus a lead time in \"Remind me this many days before\", say 45, giving a reminder on 2029-06-16. Check the source sentence, correct a misread date, or tick \"No reminder needed for this document\".",
        optional: true,
      },
      {
        key: "ai-review-save",
        route: { to: "/agency/document-vault" },
        selector: '[data-tour="filing-save"]',
        title: "Human validation required",
        body: "Nothing is ever filed automatically. \"Save filing\" writes exactly what's in the fields at that moment. \"Skip for now\" leaves the document queued under the Pending review filter on the tabs you saw earlier, so it's never lost — just waiting.",
        optional: true,
      },
    ],
  },
  {
    id: "agency.invitations",
    portal: "agency",
    kind: "module",
    title: "Inviting talent",
    description: "Send one talent invitation end to end, including the folders they'll receive.",
    match: ["/agency/invitations"],
    steps: [
      {
        key: "start",
        route: { to: "/agency/invitations" },
        selector: '[data-tour="agency-invite-actions"]',
        title: "Step 1 — Invite Talent or Invite Staff",
        body: "On Invitations, \"Invite Talent\" opens the two-step wizard — Details, then Folders. \"Invite Staff\" adds a colleague to your agency instead and has no folder step. Only the agency owner can send either.",
      },
      {
        key: "details",
        route: { to: "/agency/invitations" },
        selector: '[data-tour="agency-invite-actions"]',
        title: "Step 2 — Details",
        body: "Talent name *: \"Naledi Khumalo\" — use the full name exactly as it appears on their ID, because it's what their documents are filed under. Email *: \"naledi@example.com\". Invitation expiry (days): 7. Then continue to the Folders step.",
        optional: true,
      },
      {
        key: "folders",
        route: { to: "/agency/invitations" },
        selector: '[data-tour="agency-invite-actions"]',
        title: "Step 3 — Folders for this talent",
        body: "Two cards. \"Use my standard set\" (Recommended) provisions the folders listed as badges on the card, pulled from your default Folder Template — take this unless you have a reason not to. \"Customise for this talent\" opens the full folder list with each one marked Recommended or Optional; tick, say, \"Work Permits\" for an international booking. The counter reads \"7 folders selected\".",
        optional: true,
      },
      {
        key: "visibility",
        route: { to: "/agency/invitations" },
        selector: '[data-tour="agency-invite-actions"]',
        title: "Step 4 — what they'll actually see",
        body: "Read the banner on that step before you send: folders inside the Roster Shared Folder are visible to both of you, and the talent additionally gets a Private Vault you cannot see. Choosing folders here never gives you access to anything personal. Send the invitation — the folders are created the moment it's accepted.",
        optional: true,
      },
      {
        key: "track",
        route: { to: "/agency/invitations" },
        selector: '[data-tour="agency-invite-tabs"]',
        title: "Step 5 — track, resend, revoke",
        body: "The table shows Recipient, Email, Status, Sent By and Expires; the tabs filter to talent, staff, expired or revoked. Each recipient has a unique link. Copying the link never extends the expiry — if the row reads expired, resend rather than re-copying, or the talent hits a dead link.",
      },
    ],
  },
  {
    id: "agency.folders",
    portal: "agency",
    kind: "module",
    title: "Folders & document rules",
    description: "Set the standard folder set, its validity rules, then retention and expiry notice.",
    match: ["/agency/settings"],
    steps: [
      {
        key: "default-set",
        route: { to: "/agency/settings", search: { tab: "folders" } },
        selector: '[data-tour="manage-folders"]',
        title: "Step 1 — Default Folder Selection",
        body: "Agency Profile → Manage Folders. Tick the categories every new talent should get — Identity Documents, Contracts, Banking, Medical — and untick what your agency never handles. This is the set the invitation wizard offers as \"Use my standard set\", so getting it right here saves customising every invitation.",
      },
      {
        key: "subfolders",
        route: { to: "/agency/settings", search: { tab: "folders" } },
        selector: '[data-tour="manage-folders"]',
        title: "Step 2 — add subfolders under Folder Rules",
        body: "In the \"Folder Rules\" table, use the add action on a folder row to open \"Add a subfolder\", type a Subfolder name — for example \"Medical Clearance\" under Medical — and save. Subfolders are how you keep a folder usable once it holds twenty documents.",
        optional: true,
      },
      {
        key: "validity",
        route: { to: "/agency/settings", search: { tab: "folders" } },
        selector: '[data-tour="manage-folders"]',
        title: "Step 3 — Default Validity Rule",
        body: "Still in Folder Rules, open the \"Default Validity Rule\" cell for a folder. Choose a Preset, or type your own — \"3 years\" for a work permit. New documents filed there inherit it, so expiry is tracked even when nobody typed a date. The reset control puts a row back to the platform default.",
        optional: true,
      },
      {
        key: "retention",
        route: { to: "/agency/settings", search: { tab: "document-rules" } },
        selector: '[data-tour="document-rules"]',
        title: "Step 4 — folder retention rules",
        body: "On Document Rules, click add on \"Folder retention rules\". Scope: \"Entire folder\"; Folder: \"Contracts\"; set the retention years and a description like \"Statutory 10-year contract retention\"; \"Save rule\". Documents under that rule cannot be deleted until the period lapses — the \"Documents currently locked\" tile counts them.",
      },
      {
        key: "overrides",
        route: { to: "/agency/settings", search: { tab: "document-rules" } },
        selector: '[data-tour="document-rules"]',
        title: "Step 5 — per-document overrides",
        body: "For a single exception, add a rule with Scope \"Specific document\" and pick the document. It appears under \"Per-document overrides\" and beats the folder rule for that one file; remove the override and the folder rule applies again. Only the agency owner can edit or delete either.",
        optional: true,
      },
      {
        key: "notice",
        route: { to: "/agency/settings", search: { tab: "document-rules" } },
        selector: '[data-tour="document-rules"]',
        title: "Step 6 — expiring-document notice period",
        body: "At the bottom, set \"Notice period (days)\" to 60 and Save. A permit expiring 2027-01-31 then appears on your dashboard warning banner and in the Vault's Expiring tab from 2026-12-02 — enough time to chase a renewal rather than discover it late.",
      },
    ],
  },

  /* ----------------------------------------------------------------- admin */
  {
    id: "admin.overview",
    portal: "admin",
    kind: "overview",
    title: "Portal overview",
    description: "A quick lap of the main sections of the admin portal.",
    steps: [
      {
        key: "dashboard",
        selector: '[data-tour="/admin"]',
        title: "Dashboard",
        body: "Platform health at a glance — agencies, active talent, outstanding invites and anything needing review.",
      },
      {
        key: "agencies",
        selector: '[data-tour="/admin/agencies"]',
        title: "Agencies",
        body: "Every agency on the platform — activate, suspend and inspect their setup from here.",
      },
      {
        key: "invitations",
        selector: '[data-tour="/admin/invitations"]',
        title: "Agency Invitations",
        body: "Create and track agency invites, edit the invitation email and send or copy the secure link.",
      },
      {
        key: "quotes-invoices",
        selector: '[data-tour="/admin/quotes-invoices"]',
        title: "Quotes & Invoices",
        body: "Billing activity across the platform, aggregated from what agencies have quoted, invoiced and collected.",
      },
      {
        key: "administrators",
        selector: '[data-tour="/admin/administrators"]',
        title: "Administrators",
        body: "Manage who has platform admin access and their two-factor enrolment.",
      },
      {
        key: "audit",
        selector: '[data-tour="/admin/audit"]',
        title: "Audit & Support Log",
        body: "A full, filterable record of every privileged action, with IP and device details.",
      },
    ],
  },
  {
    id: "admin.invitations",
    portal: "admin",
    kind: "module",
    title: "Agency invitation workflow",
    description: "Create one agency invitation, field by field, then send or hand over the link.",
    match: ["/admin/invitations"],
    steps: [
      {
        key: "create",
        route: { to: "/admin/invitations" },
        selector: '[data-tour="admin-invite-actions"]',
        title: "Step 1 — start a new invitation",
        body: "On Agency Invitations, click the new-invitation button in the top right. It opens a full form rather than a modal, because the invitation carries compliance requirements with it.",
      },
      {
        key: "details",
        route: { to: "/admin/invitations/new" },
        selector: '[data-tour="admin-invite-actions"]',
        title: "Step 2 — agency details",
        body: "Agency name *: \"NewTech Talent Agency\". Primary contact person: \"Maya Johnson\". Contact email *: \"contact@agency.com\" — this is the only address the secure link is issued to, so check it character by character. Phone: \"+27 82 123 4567\".",
        optional: true,
      },
      {
        key: "business-type",
        route: { to: "/admin/invitations/new" },
        selector: '[data-tour="admin-invite-actions"]',
        title: "Step 3 — Business type drives the paperwork",
        body: "Choose Business type * before anything else on the lower half of the form: the \"Compliance documents\" list underneath rebuilds itself to match, so a sole proprietor is asked for a different set than a registered company. Change it afterwards and you'll re-do that list.",
        optional: true,
      },
      {
        key: "expiry",
        route: { to: "/admin/invitations/new" },
        selector: '[data-tour="admin-invite-actions"]',
        title: "Step 4 — expiry, then create",
        body: "Set \"Invitation expiry (days)\" to 14 — long enough for a company to gather documents, short enough that a stale link doesn't sit live for a month. Create the invitation; it lands in the list as Pending and nothing has been emailed yet.",
        optional: true,
      },
      {
        key: "template",
        route: { to: "/admin/invitations" },
        selector: '[data-tour="admin-invite-table"]',
        title: "Step 5 — edit the email before it goes",
        body: "Open the invitation's preview screen from its row. You see the message exactly as Maya will, and you can adjust the wording — add the name of the person who referred them, or the deadline you agreed on the phone. Nothing is sent while you're editing.",
        optional: true,
      },
      {
        key: "send",
        route: { to: "/admin/invitations" },
        selector: '[data-tour="admin-invite-table"]',
        title: "Step 6 — send, or copy the secure link",
        body: "Send it by email from the preview, or copy the unique link and pass it on yourself over a channel you trust. The Sends column counts each send. Copying never extends the expiry — if Expires has passed, resend to mint a fresh window rather than re-copying a dead link.",
        optional: true,
      },
      {
        key: "correct",
        route: { to: "/admin/invitations" },
        selector: '[data-tour="admin-invite-table"]',
        title: "Step 7 — a wrong address, or a cancellation",
        body: "If the email was wrong, use \"Edit invitation email\" on the row, correct Recipient email and resend — the old link stops working. To cancel, prefer Revoke over Delete: revoking keeps the audit trail, deleting removes the invitation permanently.",
        optional: true,
      },
      {
        key: "status",
        route: { to: "/admin/invitations" },
        selector: '[data-tour="admin-invite-kpis"]',
        title: "Step 8 — where each one stands",
        body: "The tiles — Total Invitations, Awaiting Acceptance, Accepted — filter the list when clicked. Work \"Awaiting Acceptance\" weekly: anything sitting there past its Expires date needs a resend or a revoke, not silence.",
        optional: true,
      },
    ],
  },
  {
    id: "admin.agencies",
    portal: "admin",
    kind: "module",
    title: "Managing agencies",
    description: "Find an agency, inspect it, and suspend or reinstate it properly.",
    match: ["/admin/agencies"],
    steps: [
      {
        key: "list",
        route: { to: "/admin/agencies" },
        selector: '[data-tour="admin-agency-table"]',
        title: "Step 1 — find the agency",
        body: "Type \"NewTech\" into \"Search agencies...\" or click a tile — Total Agencies, Accepted, Invited, Suspended — to filter. The table gives Agency, Status, Contact, Country, Talent and Created. \"Reset filters\" clears everything if the list looks emptier than it should.",
        optional: true,
      },
      {
        key: "open",
        route: { to: "/admin/agencies" },
        selector: '[data-tour="admin-agency-table"]',
        title: "Step 2 — open it and check the facts",
        body: "Click the agency row to open its detail page — members, talent count and compliance state. Do this before any action: the Talent number tells you how many people a suspension will affect. If a row is still Invited, the \"Find matching invitation\" action jumps you to the invitation instead.",
        optional: true,
      },
      {
        key: "suspend",
        route: { to: "/admin/agencies" },
        selector: '[data-tour="admin-agency-actions"]',
        title: "Step 3 — suspend, with a reason",
        body: "Choose Suspend and type the reason in full — \"Unpaid platform subscription — 60 days overdue, escalated 2026-08-14.\" It is written to the audit log with your name, and it's what the next admin will read. Suspension blocks active actions but preserves read-only access and export, so nobody loses their documents.",
        optional: true,
      },
      {
        key: "reinstate",
        route: { to: "/admin/agencies" },
        selector: '[data-tour="admin-agency-actions"]',
        title: "Step 4 — reinstating",
        body: "Activating a suspended agency restores it immediately — no re-invitation and no re-onboarding, their talent and folders are exactly as they left them. New agencies normally arrive through an invitation, so most of your work here is reviewing and reinstating rather than creating.",
      },
    ],
  },
  {
    id: "admin.quotes-invoices",
    portal: "admin",
    kind: "module",
    title: "Platform billing oversight",
    description: "Read the platform's billing figures and trace one back to its agency.",
    match: ["/admin/quotes-invoices"],
    steps: [
      {
        key: "readonly",
        route: { to: "/admin/quotes-invoices" },
        selector: '[data-tour="admin-billing-header"]',
        title: "Step 1 — this screen is read-only",
        body: "Every figure here is aggregated from the agencies' own billing. There is no create or edit action and the row action is view-only by design — quotes and invoices are raised and sent by each agency in their own portal. If a document is wrong, the agency corrects it, not you.",
      },
      {
        key: "totals",
        route: { to: "/admin/quotes-invoices" },
        selector: '[data-tour="admin-billing-kpis"]',
        title: "Step 2 — read the tiles",
        body: "Total Records, Outstanding and Overdue Invoices cover every agency for the period selected. Overdue Invoices is the one to act on: a number climbing month on month is usually one agency in trouble, not a platform-wide trend — the table below tells you which.",
        optional: true,
      },
      {
        key: "table",
        route: { to: "/admin/quotes-invoices" },
        selector: '[data-tour="admin-billing-table"]',
        title: "Step 3 — trace a figure to its source",
        body: "Type an agency name into \"Search number, client, agency...\", or set the type filter to Invoice. Each row gives Agency, Type, Number, Client, Issued, Total and Status — so \"R48,300 outstanding\" resolves to, say, three overdue invoices from one agency, which is what you'd raise with them.",
        optional: true,
      },
    ],
  },
];
