/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TalentRouteImport } from './routes/talent'
import { Route as LovedOneRouteImport } from './routes/loved-one'
import { Route as AgencyRouteImport } from './routes/agency'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgencyIndexRouteImport } from './routes/agency.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AgencyTalentRouteImport } from './routes/agency.talent'
import { Route as AgencySettingsRouteImport } from './routes/agency.settings'
import { Route as AgencyQuotesInvoicesRouteImport } from './routes/agency.quotes-invoices'
import { Route as AgencyInvitationsRouteImport } from './routes/agency.invitations'
import { Route as AgencyFolderTemplatesRouteImport } from './routes/agency.folder-templates'
import { Route as AgencyDocumentVaultRouteImport } from './routes/agency.document-vault'
import { Route as AdminInvitationsRouteImport } from './routes/admin.invitations'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAgenciesRouteImport } from './routes/admin.agencies'
import { Route as AdminAdministratorsRouteImport } from './routes/admin.administrators'
import { Route as AgencyTalentInviteRouteImport } from './routes/agency.talent.invite'
import { Route as AdminInvitationsNewRouteImport } from './routes/admin.invitations.new'
import { Route as AdminAgenciesIdRouteImport } from './routes/admin.agencies.$id'

const TalentRoute = TalentRouteImport.update({
  id: '/talent',
  path: '/talent',
  getParentRoute: () => rootRouteImport,
} as any)
const LovedOneRoute = LovedOneRouteImport.update({
  id: '/loved-one',
  path: '/loved-one',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyRoute = AgencyRouteImport.update({
  id: '/agency',
  path: '/agency',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyIndexRoute = AgencyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgencyRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AgencyTalentRoute = AgencyTalentRouteImport.update({
  id: '/talent',
  path: '/talent',
  getParentRoute: () => AgencyRoute,
} as any)
const AgencySettingsRoute = AgencySettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AgencyRoute,
} as any)
const AgencyQuotesInvoicesRoute = AgencyQuotesInvoicesRouteImport.update({
  id: '/quotes-invoices',
  path: '/quotes-invoices',
  getParentRoute: () => AgencyRoute,
} as any)
const AgencyInvitationsRoute = AgencyInvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => AgencyRoute,
} as any)
const AgencyFolderTemplatesRoute = AgencyFolderTemplatesRouteImport.update({
  id: '/folder-templates',
  path: '/folder-templates',
  getParentRoute: () => AgencyRoute,
} as any)
const AgencyDocumentVaultRoute = AgencyDocumentVaultRouteImport.update({
  id: '/document-vault',
  path: '/document-vault',
  getParentRoute: () => AgencyRoute,
} as any)
const AdminInvitationsRoute = AdminInvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgenciesRoute = AdminAgenciesRouteImport.update({
  id: '/agencies',
  path: '/agencies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdministratorsRoute = AdminAdministratorsRouteImport.update({
  id: '/administrators',
  path: '/administrators',
  getParentRoute: () => AdminRoute,
} as any)
const AgencyTalentInviteRoute = AgencyTalentInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AgencyTalentRoute,
} as any)
const AdminInvitationsNewRoute = AdminInvitationsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminInvitationsRoute,
} as any)
const AdminAgenciesIdRoute = AdminAgenciesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminAgenciesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agency': typeof AgencyRouteWithChildren
  '/loved-one': typeof LovedOneRoute
  '/talent': typeof TalentRoute
  '/admin/administrators': typeof AdminAdministratorsRoute
  '/admin/agencies': typeof AdminAgenciesRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/invitations': typeof AdminInvitationsRouteWithChildren
  '/agency/document-vault': typeof AgencyDocumentVaultRoute
  '/agency/folder-templates': typeof AgencyFolderTemplatesRoute
  '/agency/invitations': typeof AgencyInvitationsRoute
  '/agency/quotes-invoices': typeof AgencyQuotesInvoicesRoute
  '/agency/settings': typeof AgencySettingsRoute
  '/agency/talent': typeof AgencyTalentRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/agency/': typeof AgencyIndexRoute
  '/admin/agencies/$id': typeof AdminAgenciesIdRoute
  '/admin/invitations/new': typeof AdminInvitationsNewRoute
  '/agency/talent/invite': typeof AgencyTalentInviteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/loved-one': typeof LovedOneRoute
  '/talent': typeof TalentRoute
  '/admin/administrators': typeof AdminAdministratorsRoute
  '/admin/agencies': typeof AdminAgenciesRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/invitations': typeof AdminInvitationsRouteWithChildren
  '/agency/document-vault': typeof AgencyDocumentVaultRoute
  '/agency/folder-templates': typeof AgencyFolderTemplatesRoute
  '/agency/invitations': typeof AgencyInvitationsRoute
  '/agency/quotes-invoices': typeof AgencyQuotesInvoicesRoute
  '/agency/settings': typeof AgencySettingsRoute
  '/agency/talent': typeof AgencyTalentRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/agency': typeof AgencyIndexRoute
  '/admin/agencies/$id': typeof AdminAgenciesIdRoute
  '/admin/invitations/new': typeof AdminInvitationsNewRoute
  '/agency/talent/invite': typeof AgencyTalentInviteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agency': typeof AgencyRouteWithChildren
  '/loved-one': typeof LovedOneRoute
  '/talent': typeof TalentRoute
  '/admin/administrators': typeof AdminAdministratorsRoute
  '/admin/agencies': typeof AdminAgenciesRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/invitations': typeof AdminInvitationsRouteWithChildren
  '/agency/document-vault': typeof AgencyDocumentVaultRoute
  '/agency/folder-templates': typeof AgencyFolderTemplatesRoute
  '/agency/invitations': typeof AgencyInvitationsRoute
  '/agency/quotes-invoices': typeof AgencyQuotesInvoicesRoute
  '/agency/settings': typeof AgencySettingsRoute
  '/agency/talent': typeof AgencyTalentRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/agency/': typeof AgencyIndexRoute
  '/admin/agencies/$id': typeof AdminAgenciesIdRoute
  '/admin/invitations/new': typeof AdminInvitationsNewRoute
  '/agency/talent/invite': typeof AgencyTalentInviteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agency'
    | '/loved-one'
    | '/talent'
    | '/admin/administrators'
    | '/admin/agencies'
    | '/admin/audit'
    | '/admin/invitations'
    | '/agency/document-vault'
    | '/agency/folder-templates'
    | '/agency/invitations'
    | '/agency/quotes-invoices'
    | '/agency/settings'
    | '/agency/talent'
    | '/admin/'
    | '/agency/'
    | '/admin/agencies/$id'
    | '/admin/invitations/new'
    | '/agency/talent/invite'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/loved-one'
    | '/talent'
    | '/admin/administrators'
    | '/admin/agencies'
    | '/admin/audit'
    | '/admin/invitations'
    | '/agency/document-vault'
    | '/agency/folder-templates'
    | '/agency/invitations'
    | '/agency/quotes-invoices'
    | '/agency/settings'
    | '/agency/talent'
    | '/admin'
    | '/agency'
    | '/admin/agencies/$id'
    | '/admin/invitations/new'
    | '/agency/talent/invite'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agency'
    | '/loved-one'
    | '/talent'
    | '/admin/administrators'
    | '/admin/agencies'
    | '/admin/audit'
    | '/admin/invitations'
    | '/agency/document-vault'
    | '/agency/folder-templates'
    | '/agency/invitations'
    | '/agency/quotes-invoices'
    | '/agency/settings'
    | '/agency/talent'
    | '/admin/'
    | '/agency/'
    | '/admin/agencies/$id'
    | '/admin/invitations/new'
    | '/agency/talent/invite'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgencyRoute: typeof AgencyRouteWithChildren
  LovedOneRoute: typeof LovedOneRoute
  TalentRoute: typeof TalentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/talent': {
      id: '/talent'
      path: '/talent'
      fullPath: '/talent'
      preLoaderRoute: typeof TalentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loved-one': {
      id: '/loved-one'
      path: '/loved-one'
      fullPath: '/loved-one'
      preLoaderRoute: typeof LovedOneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency': {
      id: '/agency'
      path: '/agency'
      fullPath: '/agency'
      preLoaderRoute: typeof AgencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency/': {
      id: '/agency/'
      path: '/'
      fullPath: '/agency/'
      preLoaderRoute: typeof AgencyIndexRouteImport
      parentRoute: typeof AgencyRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/agency/talent': {
      id: '/agency/talent'
      path: '/talent'
      fullPath: '/agency/talent'
      preLoaderRoute: typeof AgencyTalentRouteImport
      parentRoute: typeof AgencyRoute
    }
    '/agency/settings': {
      id: '/agency/settings'
      path: '/settings'
      fullPath: '/agency/settings'
      preLoaderRoute: typeof AgencySettingsRouteImport
      parentRoute: typeof AgencyRoute
    }
    '/agency/quotes-invoices': {
      id: '/agency/quotes-invoices'
      path: '/quotes-invoices'
      fullPath: '/agency/quotes-invoices'
      preLoaderRoute: typeof AgencyQuotesInvoicesRouteImport
      parentRoute: typeof AgencyRoute
    }
    '/agency/invitations': {
      id: '/agency/invitations'
      path: '/invitations'
      fullPath: '/agency/invitations'
      preLoaderRoute: typeof AgencyInvitationsRouteImport
      parentRoute: typeof AgencyRoute
    }
    '/agency/folder-templates': {
      id: '/agency/folder-templates'
      path: '/folder-templates'
      fullPath: '/agency/folder-templates'
      preLoaderRoute: typeof AgencyFolderTemplatesRouteImport
      parentRoute: typeof AgencyRoute
    }
    '/agency/document-vault': {
      id: '/agency/document-vault'
      path: '/document-vault'
      fullPath: '/agency/document-vault'
      preLoaderRoute: typeof AgencyDocumentVaultRouteImport
      parentRoute: typeof AgencyRoute
    }
    '/admin/invitations': {
      id: '/admin/invitations'
      path: '/invitations'
      fullPath: '/admin/invitations'
      preLoaderRoute: typeof AdminInvitationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agencies': {
      id: '/admin/agencies'
      path: '/agencies'
      fullPath: '/admin/agencies'
      preLoaderRoute: typeof AdminAgenciesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/administrators': {
      id: '/admin/administrators'
      path: '/administrators'
      fullPath: '/admin/administrators'
      preLoaderRoute: typeof AdminAdministratorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/agency/talent/invite': {
      id: '/agency/talent/invite'
      path: '/invite'
      fullPath: '/agency/talent/invite'
      preLoaderRoute: typeof AgencyTalentInviteRouteImport
      parentRoute: typeof AgencyTalentRoute
    }
    '/admin/invitations/new': {
      id: '/admin/invitations/new'
      path: '/new'
      fullPath: '/admin/invitations/new'
      preLoaderRoute: typeof AdminInvitationsNewRouteImport
      parentRoute: typeof AdminInvitationsRoute
    }
    '/admin/agencies/$id': {
      id: '/admin/agencies/$id'
      path: '/$id'
      fullPath: '/admin/agencies/$id'
      preLoaderRoute: typeof AdminAgenciesIdRouteImport
      parentRoute: typeof AdminAgenciesRoute
    }
  }
}

interface AdminAgenciesRouteChildren {
  AdminAgenciesIdRoute: typeof AdminAgenciesIdRoute
}

const AdminAgenciesRouteChildren: AdminAgenciesRouteChildren = {
  AdminAgenciesIdRoute: AdminAgenciesIdRoute,
}

const AdminAgenciesRouteWithChildren = AdminAgenciesRoute._addFileChildren(
  AdminAgenciesRouteChildren,
)

interface AdminInvitationsRouteChildren {
  AdminInvitationsNewRoute: typeof AdminInvitationsNewRoute
}

const AdminInvitationsRouteChildren: AdminInvitationsRouteChildren = {
  AdminInvitationsNewRoute: AdminInvitationsNewRoute,
}

const AdminInvitationsRouteWithChildren =
  AdminInvitationsRoute._addFileChildren(AdminInvitationsRouteChildren)

interface AdminRouteChildren {
  AdminAdministratorsRoute: typeof AdminAdministratorsRoute
  AdminAgenciesRoute: typeof AdminAgenciesRouteWithChildren
  AdminAuditRoute: typeof AdminAuditRoute
  AdminInvitationsRoute: typeof AdminInvitationsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdministratorsRoute: AdminAdministratorsRoute,
  AdminAgenciesRoute: AdminAgenciesRouteWithChildren,
  AdminAuditRoute: AdminAuditRoute,
  AdminInvitationsRoute: AdminInvitationsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AgencyTalentRouteChildren {
  AgencyTalentInviteRoute: typeof AgencyTalentInviteRoute
}

const AgencyTalentRouteChildren: AgencyTalentRouteChildren = {
  AgencyTalentInviteRoute: AgencyTalentInviteRoute,
}

const AgencyTalentRouteWithChildren = AgencyTalentRoute._addFileChildren(
  AgencyTalentRouteChildren,
)

interface AgencyRouteChildren {
  AgencyDocumentVaultRoute: typeof AgencyDocumentVaultRoute
  AgencyFolderTemplatesRoute: typeof AgencyFolderTemplatesRoute
  AgencyInvitationsRoute: typeof AgencyInvitationsRoute
  AgencyQuotesInvoicesRoute: typeof AgencyQuotesInvoicesRoute
  AgencySettingsRoute: typeof AgencySettingsRoute
  AgencyTalentRoute: typeof AgencyTalentRouteWithChildren
  AgencyIndexRoute: typeof AgencyIndexRoute
}

const AgencyRouteChildren: AgencyRouteChildren = {
  AgencyDocumentVaultRoute: AgencyDocumentVaultRoute,
  AgencyFolderTemplatesRoute: AgencyFolderTemplatesRoute,
  AgencyInvitationsRoute: AgencyInvitationsRoute,
  AgencyQuotesInvoicesRoute: AgencyQuotesInvoicesRoute,
  AgencySettingsRoute: AgencySettingsRoute,
  AgencyTalentRoute: AgencyTalentRouteWithChildren,
  AgencyIndexRoute: AgencyIndexRoute,
}

const AgencyRouteWithChildren =
  AgencyRoute._addFileChildren(AgencyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AgencyRoute: AgencyRouteWithChildren,
  LovedOneRoute: LovedOneRoute,
  TalentRoute: TalentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
